name: Update Site Map and Deploy

on:
  push:
    branches:
      - main

jobs:
  update-site-map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script to generate site_map.json
        run: |
          python scripts/map_generator.py

      - name: Check if site_map.json has changed
        id: check_changes
        run: |
          if git diff --quiet data/site_map.json; then
            echo "site_map.json has not changed."
            echo "::set-output name=changed::false"
          else
            echo "site_map.json has changed."
            echo "::set-output name=changed::true"
          fi

      - name: Commit and push changes if site_map.json is modified
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add data/site_map.json
          git commit -m "Update site_map.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call-deploy-site-source:
    needs: update-site-map
    uses: ./.github/workflows/deploy-site-source.yml
